version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8081:80'
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/php
      - php-vendor:/var/www/php/vendor
      - php-node-modules:/var/www/php/node_modules

  node:
    environment:
      API_URL: ${API_URL:-http://localhost:8081}
    command: yarn run dev
