version: '3'

services:
  php:
    tty: true
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./php:/var/www/php
      - php-vendor:/var/www/php/vendor
      - php-node-modules:/var/www/php/node_modules

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  node:
    tty: true
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./client:/var/www/client
      - node-modules:/var/www/client/node_modules

volumes:
  mysql-data:
  php-vendor:
  php-node-modules:
  node-modules:
